/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Legacy (keep for /blitz-demo)
        monad: { purple: '#836EF9', dark: '#1a1a2e' },
        // ─── Claude Design palette (oklch → hex) ───
        cd: {
          bg: '#f7f5ef',
          ink: '#1a2e1f',
          moss: '#2d5a3e',
          ember: '#d4742a',
          'ember-soft': '#f5e6d4',
          sky: '#c0d5e8',
          leaf: '#3d7a52',
          paper: '#fdfcf7',
          muted: '#5c6b5f',
          line: 'rgba(26,46,31,0.12)',
          // Dark mode
          'bg-dark': '#1a2820',
          'ink-dark': '#f5f3ed',
          'moss-dark': '#8abf9a',
          'ember-dark': '#e8a36a',
        },
        // ─── Stitch / M3 tokens (kept for compatibility) ───
        tc: {
          primary: '#154212',
          'on-primary': '#ffffff',
          'primary-container': '#2d5a27',
          'on-primary-container': '#9dd090',
          'primary-fixed': '#bcf0ae',
          'primary-fixed-dim': '#a1d494',
          secondary: '#5e604d',
          'on-secondary': '#ffffff',
          'secondary-container': '#e1e1c9',
          tertiary: '#642600',
          'on-tertiary': '#ffffff',
          'tertiary-container': '#893600',
          error: '#ba1a1a',
          'on-error': '#ffffff',
          'error-container': '#ffdad6',
          'on-error-container': '#93000a',
          surface: '#fafaf4',
          'on-surface': '#1a1c19',
          'on-surface-variant': '#42493e',
          'surface-container': '#eeeee9',
          'surface-container-low': '#f4f4ee',
          'surface-container-high': '#e8e8e3',
          'surface-container-highest': '#e3e3de',
          'surface-container-lowest': '#ffffff',
          outline: '#72796e',
          'outline-variant': '#c2c9bb',
          'inverse-surface': '#2f312e',
          'inverse-on-surface': '#f1f1ec',
          'inverse-primary': '#a1d494',
          orange: '#FF6B00',
        },
      },
      fontFamily: {
        // Claude Design fonts (primary)
        'display': ['var(--font-big-shoulders)', 'var(--font-fraunces)', 'system-ui', 'sans-serif'],
        'body': ['var(--font-lexend)', 'system-ui', 'sans-serif'],
        'mono': ['var(--font-jetbrains)', 'var(--font-space-grotesk)', 'ui-monospace', 'monospace'],
        // Keep aliases
        fraunces: ['var(--font-fraunces)', 'serif'],
        lexend: ['var(--font-lexend)', 'sans-serif'],
        'space-grotesk': ['var(--font-space-grotesk)', 'sans-serif'],
        'big-shoulders': ['var(--font-big-shoulders)', 'system-ui', 'sans-serif'],
        'jetbrains': ['var(--font-jetbrains)', 'ui-monospace', 'monospace'],
        sans: ['var(--font-dm-sans)', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'tc-display': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'tc-headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'tc-headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'tc-body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'tc-body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'tc-label': ['14px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '600' }],
        'tc-label-web3': ['14px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '600' }],
        'tc-caption': ['12px', { lineHeight: '1.4', fontWeight: '500' }],
        'tc-cta': ['16px', { lineHeight: '1.0', fontWeight: '700' }],
      },
      spacing: {
        'tc-xs': '4px',
        'tc-base': '8px',
        'tc-sm': '12px',
        'tc-gutter': '16px',
        'tc-md': '24px',
        'tc-lg': '40px',
        'tc-xl': '64px',
        'tc-margin': '20px',
        'tc-margin-safe': '32px',
      },
      boxShadow: {
        'premium': '0 20px 40px rgba(45, 90, 39, 0.1)',
        'glass-inset': 'inset 0 2px 4px rgba(0,0,0,0.02), 0 8px 32px rgba(45,90,39,0.05)',
        'inner-recess': 'inset 0 2px 4px rgba(0,0,0,0.05)',
        'inner-sm': 'inset 0 1px 2px rgba(0,0,0,0.04)',
      },
      borderRadius: {
        'card': '22px',
        'pill': '999px',
      },
    },
  },
  plugins: [],
}
